services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '80:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
  server:
    build: ./nodejs
    container_name: server
    environment:
      - MONGO_URI=mongodb://db:27017/mydb
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - my-volumes:/data/db

volumes:
  my-volumes:
